sonata_admin:
    title: Xiaolongchen

sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]

        sonata.block.service.text:
        sonata.block.service.action:
        sonata.block.service.rss:

sonata_media:
    # if you don't use default namespace configuration
    class:
        media: Jca\MediaBundle\Entity\Media
        gallery: Jca\MediaBundle\Entity\Gallery
        gallery_has_media: Jca\MediaBundle\Entity\GalleryHasMedia
    default_context: default
    db_driver: doctrine_orm
    contexts:
        default:
            providers:
                - sonata.media.provider.dailymotion
                - sonata.media.provider.youtube
                - sonata.media.provider.image
                - sonata.media.provider.file

            formats:
                small: { width: 100 , quality: 70}
                big:   { width: 500 , quality: 70}
    cdn:
        server:
            path: /uploads/media

    filesystem:
        local:
            directory:  %kernel.root_dir%/../web/uploads/media
            create:     true

sonata_translation:
    locales: [fr, en, zh]
    default_locale: fr
    # here enable the types you need
    gedmo:
        enabled: true
    phpcr:
        enabled: false